### PR TITLE
Allow numbers and objects in filters

### LINKED ISSUE #16: Accept Number as valid type for filter array
Currently using a number to filter a collection query causes a PropType error, when it is actually valid. In fact, changing the number to a string to silence the warning breaks the filter.

I'm happy to contribute the fix for this, if you can confirm that this project is still being maintained? Hope so!

### PR DESCRIPTION
**Pull request by bfirsh**
For example: `filter={["thing", "==", db.doc("things/" + thing)]}`

Fixes #16

### CODE REVIEW

**Comment by lrholmes** [comment]
Thanks for tackling the issue @bfirsh! @green-arrow any chance of a merge sometime soon?

**Comment by green-arrow** [comment]
@bfirsh - First off, thanks for working on this! In looking at the docs, it looks like the third item in the array is the only one that is allowed to be a `number` or `object`. The first two are always strings, one for the field name and one for the comparison type. I'm wondering if we can write a custom prop type function that would check for an array with exactly 3 items, the first two being strings and the last being a `string`, `number`, or `object`.

It would also then be possible to write some tests for that function that verify an error is thrown if the props don't match the custom shape.

This is something like what I was thinking:

```
function isValidFirestoreQuery(props, propName) {
  // Validate that props[propName] is a valid query with 3 elements and proper types
}
```

Then the `PropType` definition would become:

```
filter: PropTypes.oneOfType([isValidFirestoreQuery, PropsTypes.arrayOf(isValidFirestoreQuery)])
```

Reference: https://reactjs.org/docs/typechecking-with-proptypes.html#react.proptypes

Relevant example from reference:

```
// You can also specify a custom validator. It should return an Error
  // object if the validation fails. Don't `console.warn` or throw, as this
  // won't work inside `oneOfType`.
  customProp: function(props, propName, componentName) {
    if (!/matchme/.test(props[propName])) {
      return new Error(
        'Invalid prop `' + propName + '` supplied to' +
        ' `' + componentName + '`. Validation failed.'
      );
    }
  },

  // You can also supply a custom validator to `arrayOf` and `objectOf`.
  // It should return an Error object if the validation fails. The validator
  // will be called for each key in the array or object. The first two
  // arguments of the validator are the array or object itself, and the
  // current item's key.
  customArrayProp: PropTypes.arrayOf(function(propValue, key, componentName, location, propFullName) {
    if (!/matchme/.test(propValue[key])) {
      return new Error(
        'Invalid prop `' + propFullName + '` supplied to' +
        ' `' + componentName + '`. Validation failed.'
      );
    }
  })
```

Please let me know if that made sense or if something about it doesn't seem right!

**Comment by bfirsh** [comment]
That makes sense. It sounds rather overkill though - will this actually catch errors that a user might make?

I haven’t got time to do such an extended fix right now. Feel free to merge this now as a quick fix, if you’d like, and I could tackle it at some point in the future. :)

**Comment by bfirsh** [comment]
Come to think of it, I'll add documentation first. That'll be much more useful than a really comprehensive propType. There isn't even documentation about filtering by references in the official docs.

**Comment by green-arrow** [comment]
@bfirsh - sounds like a plan! Let me know when you add documentation and we'll get this merged.

**Comment by bfirsh** [comment]
Okay done a couple of things:

- Added a simple example in the docs
- Changed the test to use an actual document ref instead of just an object. This will cover the more complex propType that you describe.

The precommit hook seemed to reformat the readme, so I split that out into a separate commit to make my change clear.

**Comment by green-arrow** [comment]
@bfirsh - thanks again for your work on this!

**Pull request merged**
